### PR TITLE
Fix incorrect parsing of 24:00 in parseISO (closes #1228)

### LINKED ISSUE #1228: Wrong parsed date with time at 24:00:00
Hey,

Using date-fns-2.0.0-beta.1, it seems to not parse date correctly if there is a time like 24:00:00.

`new Date("2000-01-01T24:00:00.0")` => Jan 02 2000 00:00:00
`parse("2000-01-01T24:00:00.0")` => Jan 01 2000 00:00:00

Thank you

### PR DESCRIPTION
**Pull request by leshakoss**
According to ISO 8601 '24:00' is supposed to be parsed as 12 AM the _next_ day, but before it was parsed as 12 AM of the _same_ day. See #1228

Also a few code style fixes.

ISO 8601:2004(E)
4.2.3
```
NOTE 1 The end of one calendar day [24:00] coincides with [00:00] at the start of the next calendar day, e.g. [24:00] on 12 April 1985 is the same as [00:00] on 13 April 1985.
```

### CODE REVIEW

File: src/parseISO/index.js [hunk 1]
```diff
@@ -213,7 +213,7 @@ function parseDate(dateString, year) {
   var dayOfYear = parseDateUnit(captures[1])
   var month = parseDateUnit(captures[2]) - 1
   var day = parseDateUnit(captures[3])
-  var week = parseDateUnit(captures[4]) - 1
```
Comment (leshakoss) [inline src/parseISO/index.js]: Not sure why weeks were zero-indexed before, as they are one-indexed in our own week functions.

File: src/parseISO/index.js [hunk 2]
```diff
@@ -284,7 +284,7 @@ function dayOfISOWeekYear(isoWeekYear, week, day) {
   var date = new Date(0)
   date.setUTCFullYear(isoWeekYear, 0, 4)
   var fourthOfJanuaryDay = date.getUTCDay() || 7
-  var diff = (week || 0) * 7 + (day || 0) + 1 - fourthOfJanuaryDay
```
Comment (leshakoss) [inline src/parseISO/index.js]: Hmm, I wonder what those were for

File: src/parseISO/index.js [hunk 3]
```diff
@@ -299,33 +299,33 @@ function isLeapYearIndex(year) {
 }
 
 function validateDate(year, month, date) {
-  return !(
```
Comment (leshakoss) [inline src/parseISO/index.js]: Expanded the brackets and changed this weird negative logic

File: src/parseISO/index.js [hunk 4]
```diff
@@ -251,7 +251,7 @@ function parseTime(timeString) {
   }
 
   return (
-    (hours % 24) * MILLISECONDS_IN_HOUR +
+    hours * MILLISECONDS_IN_HOUR +
```
Comment (leshakoss) [inline src/parseISO/index.js]: The actual change of this PR 👆

File: src/parseISO/test.js [hunk 5]
```diff
@@ -292,9 +287,17 @@ describe('parseISO', () => {
...
     describe('time', () => {
-      it('parses 24:00 as midnight', () => {
+      it('parses 24:00 as midnight of the next day', () => {
         const result = parseISO('2014-02-11T24:00')
-        assert.deepEqual(result, new Date(2014, 1 /* Feb */, 11, 0, 0))
+        assert.deepEqual(result, new Date(2014, 1 /* Feb */, 12, 0, 0))
+      })
+
+      it('parses 24:mm as correct time of the next day', () => {
+        const result = parseISO('2014-02-11T24:59:59.999')
```
Comment (kossnocorp) [inline src/parseISO/test.js]: Interestingly enough, `Date.parse('2014-02-11T24:59:59.999')` returns `NaN` on that one.
