### PR TITLE
Throw invalid argument exception in eachDay and isWithinRange (closes #92)

### LINKED ISSUE #92: Add a check in `eachDay` function if end date is before start date
Throw exception in:
* eachDay
* isWithinRange

### PR DESCRIPTION
**Pull request by LeshaKoss**

### CODE REVIEW

File: src/is_within_range.js [hunk 1]
```diff
@@ -20,12 +21,17 @@ var parse = require('./parse')
...
-  return(
-    time >= parse(dirtyStartDate).getTime()
-    && time <= parse(dirtyEndDate).getTime()
-  )
+  var time = parse(dirtyDate).getTime()
+  var startTime = parse(dirtyStartDate).getTime()
+  var endTime = parse(dirtyEndDate).getTime()
+
+  if (startTime > endTime) {
+    var err = new Error('Argument dirtyStartDate must be before dirtyEndDate')
```
Comment (kossnocorp) [inline src/is_within_range.js]: 1. Error message could be better. It should explain explicitly what "before" means.
2. In JSDoc comment arguments can be named in more friendly way (`date` instead of `dirtyDate`, `startRangeDate` or `leftRangeDate` instead of `dirtyStartDate` etc). Also it makes sense to change it everywhere in the library.

Comment (LeshaKoss) [inline src/is_within_range.js]: 1.
2. I opened an issue for friendlier JSDoc arguments: #104
